services:
  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "deadline-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
        - deadline-pgdata:/var/lib/postgresql/data
        - ./init-db-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes: 
  deadline-pgdata:
