CREATE TABLE Tasks (
  id serial GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  notified int DEFAULT 0,
  start timestamptz NOT NULL,
  finish timestamptz NOT NULL
);

--CREATE TABLE Users (
--  id serial GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--  name text UNIQUE NOT NULL,
--  chatId text
--);

CREATE TABLE Groups (
  id serial GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text
);

CREATE TABLE UsersTasks (
  userId int NOT NULL,
  taskId int NOT NULL,
  done bool NOT NULL DEFAULT FALSE,
  
  constraint PK_UsersTasks PRIMARY KEY (userId, taskId)
);

CREATE TABLE GroupsTasks (
  groupId int NOT NULL,
  taskId int NOT NULL,
  
  constraint PK_GroupsTasks PRIMARY KEY (groupId, taskId)
);

CREATE TABLE UsersGroups (
  userId int NOT NULL,
  groupId int NOT NULL,
  
  constraint PK_UsersGroups PRIMARY KEY (userId, groupId)
);

CREATE INDEX ON Tasks (finish);

--ALTER TABLE UsersTasks ADD FOREIGN KEY (userId) REFERENCES Users (id);

ALTER TABLE UsersTasks ADD FOREIGN KEY (taskId) REFERENCES Tasks (id);

ALTER TABLE GroupsTasks ADD FOREIGN KEY (groupId) REFERENCES Groups (id);

ALTER TABLE GroupsTasks ADD FOREIGN KEY (taskId) REFERENCES Tasks (id);

ALTER TABLE UsersGroups ADD FOREIGN KEY (groupId) REFERENCES Groups (id);

--ALTER TABLE UsersGroups ADD FOREIGN KEY (userId) REFERENCES Users (id);
