CREATE TABLE Tasks (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  notified int DEFAULT 0,
  start timestamptz NOT NULL,
  finish timestamptz NOT NULL
);

--CREATE TABLE Users (
--  id serial GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--  name text UNIQUE NOT NULL,
--  chatId text
--);

CREATE TABLE Tags (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text
);

CREATE TABLE UsersTasks (
  userId int NOT NULL,
  taskId int NOT NULL,
  done bool NOT NULL DEFAULT FALSE,
  
  constraint PK_UsersTasks PRIMARY KEY (userId, taskId)
);

CREATE TABLE TagsTasks (
  tagId int NOT NULL,
  taskId int NOT NULL,
  
  constraint PK_TagsTasks PRIMARY KEY (tagId, taskId)
);

CREATE TABLE UsersTags (
  userId int NOT NULL,
  tagId int NOT NULL,
  
  constraint PK_UsersTags PRIMARY KEY (userId, tagId)
);

CREATE INDEX ON Tasks (finish);

--ALTER TABLE UsersTasks ADD FOREIGN KEY (userId) REFERENCES Users (id);

ALTER TABLE UsersTasks ADD FOREIGN KEY (taskId) REFERENCES Tasks (id);

ALTER TABLE TagsTasks ADD FOREIGN KEY (tagId) REFERENCES Tags (id);

ALTER TABLE TagsTasks ADD FOREIGN KEY (taskId) REFERENCES Tasks (id);

ALTER TABLE UsersTags ADD FOREIGN KEY (tagId) REFERENCES Tags (id);

--ALTER TABLE UsersTags ADD FOREIGN KEY (userId) REFERENCES Users (id);
